# Introduction
  This chapter opens the main topic and focus of this study. The introduction presents the general information and knowledge, problem statement, significance, and the scope and delimitation of the study.
    
## Background of the Study
  Recommender systems are machine learning systems that help users  discover new products and services. Recommender systems are an essential feature in our digital world, as users are often overwhelmed by choice and need help finding what they're looking for (Shetty, 2021).  A recommender system is a type of information filtering system. By drawing from huge data sets, the system’s algorithm can pinpoint accurate user preferences. Once you know what your users like, you can recommend new, relevant content. And that’s true for everything from movies and music, to romantic partners. Netflix, YouTube, Tinder, and Amazon are all examples of recommender systems in use. The systems entice users with relevant suggestions based on the choices they make (Severt, 2020). A Recommender System is composed of two modules: a database and a filtering technique. The database is responsible for storing information about users, items, and the associated ratings. The filtering technique is composed of an algorithm, generally split into two stages. On the first, the similarities between users or items are identified providing a neighborhood of each item or user. At the second stage, the system predicts ratings corresponding to the items unseen by the user, and only the best ones are used as a recommendation (Bobadilla et al., 2013). As a result of research, several types of filtering algorithms have been developed: Collaborative filtering, Content-based filtering, Demographic filtering, Social filtering, Hybrid filtering (Zhou et al., 2011). The main focus of this study is on collaborative filtering.
  Collaborative filtering is a type of personalized recommendation strategy that identifies the similarities between users (based on site interactions) to serve relevant product recommendations across digital properties. Recommender systems collect user information, mining this data to inform which items to display (Retta, 2020). Collaborative Filtering doesn’t need a good amount of information of item’s features (for example in a movie, it can be movie attributes such as genre, year, director, actor, etc.) except users’ historical preference on a set of items. Because it’s based on historical data, the core assumption here is that the users who have agreed in the past tend to also agree in the future (Luo, 2019). In collaborative filtering, there are several types of methods in dealing with the data but in this study, the clustering method is utilized. The method of identifying similar groups of data in a dataset is called clustering. It is one of the most popular techniques in data science. Entities in each group are comparatively more similar to entities of that group than those of the other groups. Clustering is the task of dividing the population or data points into a number of groups such that data points in the same groups are more similar to other data points in the same group than those in other groups. In simple words, the aim is to segregate groups with similar traits and assign them into clusters (Kaushik, 2020). There are plenty of examples of recommendation systems. It may be a book recommendation system, song recommendation system, or movies recommendation system. In the case of this study, we are going to build an anime recommendation system.
  The word anime is an abbreviation of the word animation. In Japan, the word is used to refer to all animation. However, outside of Japan, it has become the catch-all term for animation from Japan. Anime was produced by and for Japan — a local product, with a distinct look-and-feel to not just the artwork but the storytelling, the themes, and the concepts. Over the last forty years, it has become an international phenomenon, attracting millions of fans and being translated into many languages. It's tempting to think of anime as a genre. It isn't, at least no more than the animation itself is a genre, but rather a description of how the material is produced. Anime shows, like books or movies, fall into any number of existing genres: comedy, drama, sci-fi, action-adventure, horror, and so on (Yegulalp, 2018).
  This study focuses on building an anime recommendation system using collaborative filtering. We call this recommendation system as AniCom. In this study, we are dealing with different user ratings in building the prediction preference of users. This allows users or anime watchers to discover new items that they preferred watching among the diversity of anime available. We were able to identify users’ specific interests and use that information in the context of the Recommendation system.
    
## 1.2	Statement of the Problem
  This study aimed to investigate the collaborative filtering recommendation system in predicting preferences. Specifically, it aims to achieve the following:
 •	Build a collaborative filtering recommendation system using a clustering algorithm.
 •	Build a recommendation system for anime.
 •	Build and implement recommendation system using python.

## 1.3	Significance of the study
  The study discusses a collaborative filtering recommendation system using the clustering algorithm. The findings of this study will serve as additional literature about recommendation systems. The result of this study will be of great benefit to the recommendation system users, developers, and future researchers.
  •	**Users**. It is most helpful in recommendation system users in finding items of their interest. Specifically, it is helpful for anime watchers and fans who want to discover more anime to watch based on their preference.
  •	**Developers**. The concept discussed in this topic will enable the developer to explore other possible machine learning algorithms.
  •	**Future researchers**. This study may be helpful for students and future researchers as an additional reference for the topic of the recommendation system. It is significant for future researchers who want to research machine learning and build a collaborative filtering recommendation system.
  
## 1.4	Scope and delimitation
  The study mainly focused on building a recommendation system for anime. It makes use of secondary data and uses machine learning for the implementation of recommendation systems. The process included were clustering method, data preprocessing, exploratory data analysis, etc. However, the study will not focus on how to collect and generate the data since this study uses the secondary data found in the reliable database on the internet. It is only limited to collaborative filtering using a clustering algorithm. This means that other types of recommendation systems will not be implemented and other methods in dealing with the data aside from clustering algorithm will not be performed. Furthermore, this study focuses only on building an anime recommendation system. This study might not be applicable in other recommendation systems (e.g. Book recommendation system, movie recommendation system, etc.). And lastly, the recommendation system is limited to python machine programming language. Another machine programming language (such as R, Java, and C++) is not implemented.



